### ISSUE TITLE
Comentar inicio del servicio

### ISSUE THREAD

**Issue by fermatrix** [Erojase/odoo-dockerfile#3]
https://github.com/Erojase/odoo-dockerfile/blob/001baa98e8857ac204a7a0864a1283bb67241585/14.0/Dockerfile#L57

Ahora que ya sabemos que podemos iniciar el servicio si queremos, yo dejaría esa linea comentada y le pondría un comentario indicando lo que hace.

La razón es que para desarrollar es un poco rollo porque lo primero que tienes que hacer al entrar a la máquina es detener el servicio y si eso luego arrancarlo con la funcionalidad de Debug de Visual Code

**Comment by Erojase** [comment]
Hecho
